# Site settings
title: Sfsiuong
header-img: "img/1.jpg"
tagline: "cn"
description: "Stoney|读·写"
baseurl: ""
url: "http://jjx"

# About/contact
owner:
  name: " stoney"
  email: stoney0616@126.com
  bio: "记录生活"

# Data
gavatar: img/favicon.png
favicon: img/favicon.png

douban_username:
twitter_username:
github_username: sfsiuong
facebook_username:
weibo_username:
zhihu_username:

# Build settings
# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
gems: [jekyll-paginate]
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "stoney"
      header-img: "img/6.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments
comments :
  provider : duoshuo
  duoshuo :
    short_name :
  disqus :
      short_name :

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
